#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#  @copyright 2018 TUNE, Inc. (http://www.tune.com)
#  @namespace smart-cast

from safe_cast import (safe_int, safe_float, safe_str, safe_dict, safe_cost, safe_fraction)

print("\n")
print('==================================')
print('safe_str()')
print('==================================')
print(safe_str(.1))
print(safe_str(.12))
print(safe_str(.123))
print(safe_str(.1234))
print(safe_str(.12345))
print(safe_str(4))
print(safe_str('4'))
print(safe_str('4.0'))
print(safe_str(4.0))

print("\n")
print('==================================')
print('safe_int()')
print('==================================')
print(safe_int(.1))
print(safe_int(.12))
print(safe_int(.123))
print(safe_int(.1234))
print(safe_int(.12345))
print(safe_int(4))
print(safe_int('4'))
print(safe_int(4.0))
print(safe_int('4.0'))
print(safe_int('1.0'))
print(safe_int('1'))
print(safe_int(1.0))
print(safe_int(1.00))
print(safe_int(1))
print(safe_int('4.1'))
print(safe_int('4.12'))
print(safe_int('4.123'))
print(safe_int('4.123'))
print(safe_int('4.1234'))
print(safe_int('4.12345'))
print(safe_int(4.1))
print(safe_int(4.12))
print(safe_int(4.123))
print(safe_int(4.123))
print(safe_int(4.1234))
print(safe_int(4.12345))

print("\n")
print('==================================')
print('safe_float()')
print('==================================')
print(safe_float(.1))
print(safe_float(.12))
print(safe_float(.123))
print(safe_float(.1234))
print(safe_float(.12345))
print(safe_float(4))
print(safe_float('4'))
print(safe_float(4.0))
print(safe_float('4.0'))
print(safe_float('4.'))
print(safe_float('4.1'))
print(safe_float('4.12'))
print(safe_float('4.123'))
print(safe_float('4.123', 4))
print(safe_float('4.1234', 4))
print(safe_float('4.12345', 4))
print(safe_float(4))
print(safe_float(4.1))
print(safe_float(4.12))
print(safe_float(4.123))
print(safe_float(4.123, 4))
print(safe_float(4.1234, 4))
print(safe_float(4.12345, 4))

print("\n")
print('==================================')
print('safe_cost()')
print('==================================')
print(safe_cost(.1))
print(safe_cost(.12))
print(safe_cost(.123))
print(safe_cost(.1234))
print(safe_cost(.12345))
print(safe_cost(4))
print(safe_cost(4.1))
print(safe_cost(4.12))
print(safe_cost(4.123))
print(safe_cost(4.1234))
print(safe_cost(4.12345))

print("\n")
print('==================================')
print('safe_dict()')
print('==================================')
print(safe_dict({'key': 'value'}))

print("\n")
print('==================================')
print('safe_fraction()')
print('==================================')
print(safe_fraction("1/2"))

print("\n")
print('==================================')
print('ValueError')
print('==================================')
try:
    safe_int("apple")
except ValueError as ex:
    print(str(ex))

try:
    safe_dict("apple")
except ValueError as ex:
    print(str(ex))

try:
    safe_float({'key': 'value'})
except TypeError as ex:
    print(str(ex))
